package pojo;
// Generated Sep 24, 2024 10:15:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus  implements java.io.Serializable {


     private Integer idBus;
     private String noBody;
     private String platNomor;
     private String tipeBus;
     private String pemilik;
     private String status;
     private Set fleets = new HashSet(0);

    public Bus() {
    }

	
    public Bus(String noBody, String platNomor, String tipeBus, String pemilik, String status) {
        this.noBody = noBody;
        this.platNomor = platNomor;
        this.tipeBus = tipeBus;
        this.pemilik = pemilik;
        this.status = status;
    }
    public Bus(String noBody, String platNomor, String tipeBus, String pemilik, String status, Set fleets) {
       this.noBody = noBody;
       this.platNomor = platNomor;
       this.tipeBus = tipeBus;
       this.pemilik = pemilik;
       this.status = status;
       this.fleets = fleets;
    }
   
    public Integer getIdBus() {
        return this.idBus;
    }
    
    public void setIdBus(Integer idBus) {
        this.idBus = idBus;
    }
    public String getNoBody() {
        return this.noBody;
    }
    
    public void setNoBody(String noBody) {
        this.noBody = noBody;
    }
    public String getPlatNomor() {
        return this.platNomor;
    }
    
    public void setPlatNomor(String platNomor) {
        this.platNomor = platNomor;
    }
    public String getTipeBus() {
        return this.tipeBus;
    }
    
    public void setTipeBus(String tipeBus) {
        this.tipeBus = tipeBus;
    }
    public String getPemilik() {
        return this.pemilik;
    }
    
    public void setPemilik(String pemilik) {
        this.pemilik = pemilik;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getFleets() {
        return this.fleets;
    }
    
    public void setFleets(Set fleets) {
        this.fleets = fleets;
    }

    @Override
    public String toString() {
        return "Bus ID: " + idBus + ", Plate Number: " + platNomor + ", Type: " + tipeBus;
    }


}


