package pojo;

// Generated Sep 24, 2024 10:15:07 AM by Hibernate Tools 4.3.1

/**
 * Fleet generated by hbm2java
 */
public class Fleet implements java.io.Serializable {

    private Integer idFleet;
    private Bus bus;
    private Driver driver;
    private Rute rute;

    public Fleet() {
    }

    public Fleet(Bus bus, Driver driver, Rute rute) {
        this.bus = bus;
        this.driver = driver;
        this.rute = rute;
    }

    public Integer getIdFleet() {
        return this.idFleet;
    }

    public void setIdFleet(Integer idFleet) {
        this.idFleet = idFleet;
    }

    public Bus getBus() {
        return this.bus;
    }

    public void setBus(Bus bus) {
        this.bus = bus;
    }

    public Driver getDriver() {
        return this.driver;
    }

    public void setDriver(Driver driver) {
        this.driver = driver;
    }

    public Rute getRute() {
        return this.rute;
    }

    public void setRute(Rute rute) {
        this.rute = rute;
    }
}    