package pojo;
// Generated Sep 24, 2024 10:15:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rute generated by hbm2java
 */
public class Rute  implements java.io.Serializable {


     private String idRute;
     private String jurusan;
     private Set fleets = new HashSet(0);

    public Rute() {
    }

	
    public Rute(String idRute, String jurusan) {
        this.idRute = idRute;
        this.jurusan = jurusan;
    }
    public Rute(String idRute, String jurusan, Set fleets) {
       this.idRute = idRute;
       this.jurusan = jurusan;
       this.fleets = fleets;
    }
   
    public String getIdRute() {
        return this.idRute;
    }
    
    public void setIdRute(String idRute) {
        this.idRute = idRute;
    }
    public String getJurusan() {
        return this.jurusan;
    }
    
    public void setJurusan(String jurusan) {
        this.jurusan = jurusan;
    }
    public Set getFleets() {
        return this.fleets;
    }
    
    public void setFleets(Set fleets) {
        this.fleets = fleets;
    }

    @Override
    public String toString() {
        return "Route ID: " + idRute + ", Destination: " + jurusan;
    }


}


